name: Pipeline Template

on:
  workflow_call:
    inputs:
      environment:
        description: 'GitHub environment'
        default: development
        type: string
      project-name:
        description: 'Name of the project'
        required: true
        type: string

# https://docs.github.com/en/actions/using-workflows/reusing-workflows
jobs:
  build_test:
    uses: ./.github/workflows/_build-test.yml
    with:
      environment: ${{ inputs.environment }}
      project-name: ${{ inputs.project-name }}
      configuration: Release
    secrets: inherit

  deploy:
    if: ${{ inputs.environment == 'release' }} # && {{ github.event_name != 'pull_request' }}
    needs: build_test
    uses: ./.github/workflows/_deploy-nuget.yml
    with:
      environment: ${{ inputs.environment }}
      project-name: ${{ inputs.project-name }}
      version: ${{ needs.build_test.outputs.version }}
    secrets: inherit
