name: "Build and Test"

on:
  push:
    branches:
    - 'develop'
    # - 'main'

env:
  PROJECT_NAME: 'MailKitSimplified'
  PROJECT_CORE: 'MailKitSimplified.Core'
  PROJECT_SENDER: 'MailKitSimplified.Sender'

jobs:
  dotnet_test:
    runs-on: ubuntu-latest

    env:
      SOLUTION_FILE: 'samples/MailKitSimplified.Sender.sln'
      PROJECT_CORE_FILE: 'source/MailKitSimplified.Core/MailKitSimplified.Core.csproj'
      PROJECT_SENDER_FILE: 'source/MailKitSimplified.Sender/MailKitSimplified.Sender'

    steps:
    - name: Get full repository history
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true  

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine version from repository history
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Markdown workflow job summary
      run: echo "### $Workflow_Name $GITHUB_EVENT_NAME build summary" >> $GITHUB_STEP_SUMMARY
      env:
        Workflow_Name: "${{ github.repository }} version ${{ steps.gitversion.outputs.fullSemVer }}"

    - name: Setup .NET environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $SOLUTION_FILE

    - name: Build
      run: dotnet build $SOLUTION_FILE --configuration Release --no-restore -p:Version=${{ steps.gitversion.outputs.majorMinorPatch }}

    # The "--logger trx" option causes duplicate folders and xml files to be created
    # "coverlet.collector" package is included in the "xUnit" test project
    - name: Test
      run: dotnet test $SOLUTION_FILE -c Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory "./.coverage"

    # Using ** finds duplicate coverage files if "--logger trx" was used whereas * should not
    # "dotnet-coverage" included in "dotnet-reportgenerator-globaltool"
    - name: Summarise Code Coverage results
      run: |
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:".coverage/*/coverage.cobertura.xml" -targetdir:".coverage/CodeCoverageReport" -reporttypes:'Cobertura'

    # Based on https://github.com/irongut/CodeCoverageSummary#net-workflow-example
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ".coverage/CodeCoverageReport/Cobertura.xml"
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Markdown code coverage job summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: Pack
      run: |
        dotnet pack $Env:PROJECT_CORE_FILE -c Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} --output ".nupkg"
        dotnet pack $Env:PROJECT_SENDER_FILE -c Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersion }} --output ".nupkg"

    - name: Markdown workflow job summary
      run: |
        echo "### Packed ${{ github.event.repository.name }}" >> $GITHUB_STEP_SUMMARY
        echo " * $Core_Package_Name" >> $GITHUB_STEP_SUMMARY
        echo " * $Sender_Package_Name" >> $GITHUB_STEP_SUMMARY
      env:
        Core_Package_Name: "$Env:PROJECT_CORE.${{ steps.gitversion.outputs.nuGetVersion }}"
        Sender_Package_Name: "$Env:PROJECT_SENDER.${{ steps.gitversion.outputs.nuGetVersion }}"

    - name: Zip .nupkg directory
      run: Compress-Archive -CompressionLevel Fastest -Path ".nupkg/*" -DestinationPath "./$Env.PROJECT_NAME.zip"

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.PROJECT_NAME }}
        path: './${{ env.PROJECT_NAME }}.zip'
