name: Development

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/**

jobs:
  version:
    uses: ./.github/workflows/_gitversion.yml
    secrets: inherit

  build_core:
    needs: version
    uses: ./.github/workflows/_build-test.yml
    with:
      project-name: 'MailKitSimplified.Core'
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  build_sender:
    needs: version
    uses: ./.github/workflows/_build-test.yml
    with:
      project-name: 'MailKitSimplified.Sender'
      version: ${{ needs.version.outputs.version }}
    secrets: inherit

  build_receiver:
    needs: version
    uses: ./.github/workflows/_build-test.yml
    with:
      project-name: 'MailKitSimplified.Receiver'
      version: ${{ needs.version.outputs.version }}
    secrets: inherit
