name: Development

on:
  workflow_dispatch:
  # Run tests for any PRs.
  pull_request:
    types:
      - closed
    branches:
      - release/*
  push:
    branches:
      - main
    # Publish 'v1.2.3' tags as releases.
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

# env:
#   VERSION: ${GITHUB_REF##*v}

jobs:
  pipeline:
    # if: ${{ github.event.pull_request.merged == true }}
    name: CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: development
    secrets: inherit