name: Development

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pipeline:
    # if: ${{ github.event.pull_request.merged == true }}
    name: CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: development
    secrets: inherit