name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
    # # Publish 'v1.2.3' tags as releases.
    # tags:
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  VERSION: ${GITHUB_REF##*v}

jobs:
  pipeline:
    name: CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: release
    secrets: inherit