name: Release
run-name: Publish 'v1.2.3' tags as releases

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/**
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  pipeline:
    name: CI/CD
    uses: ./.github/workflows/_pipeline.yml
    with:
      environment: release
    secrets: inherit
